import shutil
from pathlib import Path

from setuptools import setup

# Remove stale exciton.egg-info directory to avoid
# https://github.com/pypa/pip/issues/5466
stale_egg_info = Path(__file__).parent / "exciton.egg-info"
if stale_egg_info.exists():
    print(
        (
            "Warning: {} exists.\n\n"
            "This directory is automatically generated by Python packaging tools.\n"
            "See https://github.com/pypa/pip/issues/5466 for details.\n"
        ).format(stale_egg_info)
    )
    shutil.rmtree(stale_egg_info)

dep_packages = []
with open("requirements.txt", "r") as fp:
    for line in fp:
        if line[0] != "#":
            dep_packages.append(str(line.strip()))

__version__ = "2.0.7"

setup(
    name="exciton",
    version=__version__,
    keywords="exciton NLP Deep Learning",
    description="Domain-specific Natural Language Processing with exciton",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Intended Audience :: Science/Research",
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    url="https://exciton.com",
    author="The ExcitonX Team",
    author_email="excitonx@gmail.com",
    package_dir={"": "."},
    package_data={".": ["*.txt"]},
    exclude_package_data={
        "exciton": ["trainer/*", "trainer/*/*", "research/*", "research/*/*"]
    },
    include_package_data=True,
    packages=[
        "exciton",
        "exciton.ml",
        "exciton.ml.classification",
        "exciton.ml.classification.xlm_roberta",
        "exciton.ml.engine",
        "exciton.ml.tagging",
        "exciton.ml.tagging.bert",
        "exciton.nlp",
        "exciton.nlp.event_detection",
        "exciton.nlp.lang_detection",
        "exciton.nlp.named_entity_recognition",
        "exciton.nlp.sentence_tokenizer",
        "exciton.nlp.text_matching",
        "exciton.nlp.topic_relevance",
        "exciton.nlp.translation",
        "exciton.nlp.translation.m2m100",
    ],
    install_requires=dep_packages,
    setup_requires=["pytest-runner"],
    python_requires=">=3.8",
    zip_safe=False,
)
